name: odup
on:
  watch:
    types: [started]
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 360
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
