name: onedrive_upload
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai
  ali: ${{ secrets.ALI }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: upload onedrive
         run: |
           chmod +x Upload/Upload_OneDrive.sh &&./Upload/Upload_OneDrive.sh
