name: debugger-actioe
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai
  ali: ${{ secrets.ALI }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        
      - name: upload aliyunpan
        run: |
          cd $GITHUB_WORKSPACE
          wget https://github.com/Hidove/aliyundrive-uploader/releases/download/v2021.0919.2000/aliyundrive-uploader_linux_amd64.zip
          unzip aliyundrive-uploader_linux_amd64.zip
          chmod +x aliyundrive-uploader_linux_amd64
          cat>config.json<<EOF
          ${{ secrets.ALI }}
          EOF
          ./aliyundrive-uploader_linux_amd64
